/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_window1_gestion (void)
{
  GtkWidget *window1_gestion;
  GtkWidget *fixed1;
  GtkWidget *label1;
  GtkWidget *button_supprimer_gestion;
  GtkWidget *alignment3;
  GtkWidget *hbox3;
  GtkWidget *image3;
  GtkWidget *label4;
  GtkWidget *button_modifier_gestion;
  GtkWidget *alignment2;
  GtkWidget *hbox2;
  GtkWidget *image2;
  GtkWidget *label3;
  GtkWidget *button_ajout_gestion;
  GtkWidget *alignment1;
  GtkWidget *hbox1;
  GtkWidget *image1;
  GtkWidget *label2;
  GtkWidget *treeview1;
  GtkWidget *button_rechercher_gestion;
  GtkWidget *alignment4;
  GtkWidget *hbox4;
  GtkWidget *image4;
  GtkWidget *label5;
  GtkWidget *button_deconnexion_gestion;
  GtkWidget *alignment19;
  GtkWidget *hbox19;
  GtkWidget *image19;
  GtkWidget *label43;
  GtkWidget *button_hors_norme;
  GtkWidget *alignment20;
  GtkWidget *hbox20;
  GtkWidget *image20;
  GtkWidget *label44;

  window1_gestion = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window1_gestion), _("Gestion de capteur"));

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (window1_gestion), fixed1);

  label1 = gtk_label_new (_("Bienvenue au gestion de capteur"));
  gtk_widget_show (label1);
  gtk_fixed_put (GTK_FIXED (fixed1), label1, 344, 24);
  gtk_widget_set_size_request (label1, 320, 48);

  button_supprimer_gestion = gtk_button_new ();
  gtk_widget_show (button_supprimer_gestion);
  gtk_fixed_put (GTK_FIXED (fixed1), button_supprimer_gestion, 784, 256);
  gtk_widget_set_size_request (button_supprimer_gestion, 216, 56);

  alignment3 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment3);
  gtk_container_add (GTK_CONTAINER (button_supprimer_gestion), alignment3);

  hbox3 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox3);
  gtk_container_add (GTK_CONTAINER (alignment3), hbox3);

  image3 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image3);
  gtk_box_pack_start (GTK_BOX (hbox3), image3, FALSE, FALSE, 0);

  label4 = gtk_label_new_with_mnemonic (_("Supprimer un capteur"));
  gtk_widget_show (label4);
  gtk_box_pack_start (GTK_BOX (hbox3), label4, FALSE, FALSE, 0);

  button_modifier_gestion = gtk_button_new ();
  gtk_widget_show (button_modifier_gestion);
  gtk_fixed_put (GTK_FIXED (fixed1), button_modifier_gestion, 784, 168);
  gtk_widget_set_size_request (button_modifier_gestion, 216, 56);

  alignment2 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment2);
  gtk_container_add (GTK_CONTAINER (button_modifier_gestion), alignment2);

  hbox2 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox2);
  gtk_container_add (GTK_CONTAINER (alignment2), hbox2);

  image2 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image2);
  gtk_box_pack_start (GTK_BOX (hbox2), image2, FALSE, FALSE, 0);

  label3 = gtk_label_new_with_mnemonic (_("Modifier un capteur"));
  gtk_widget_show (label3);
  gtk_box_pack_start (GTK_BOX (hbox2), label3, FALSE, FALSE, 0);

  button_ajout_gestion = gtk_button_new ();
  gtk_widget_show (button_ajout_gestion);
  gtk_fixed_put (GTK_FIXED (fixed1), button_ajout_gestion, 784, 80);
  gtk_widget_set_size_request (button_ajout_gestion, 216, 56);

  alignment1 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (button_ajout_gestion), alignment1);

  hbox1 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox1);
  gtk_container_add (GTK_CONTAINER (alignment1), hbox1);

  image1 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image1);
  gtk_box_pack_start (GTK_BOX (hbox1), image1, FALSE, FALSE, 0);

  label2 = gtk_label_new_with_mnemonic (_("Ajouter un capteur"));
  gtk_widget_show (label2);
  gtk_box_pack_start (GTK_BOX (hbox1), label2, FALSE, FALSE, 0);

  treeview1 = gtk_tree_view_new ();
  gtk_widget_show (treeview1);
  gtk_fixed_put (GTK_FIXED (fixed1), treeview1, 16, 64);
  gtk_widget_set_size_request (treeview1, 736, 392);

  button_rechercher_gestion = gtk_button_new ();
  gtk_widget_show (button_rechercher_gestion);
  gtk_fixed_put (GTK_FIXED (fixed1), button_rechercher_gestion, 784, 336);
  gtk_widget_set_size_request (button_rechercher_gestion, 216, 56);

  alignment4 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment4);
  gtk_container_add (GTK_CONTAINER (button_rechercher_gestion), alignment4);

  hbox4 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox4);
  gtk_container_add (GTK_CONTAINER (alignment4), hbox4);

  image4 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image4);
  gtk_box_pack_start (GTK_BOX (hbox4), image4, FALSE, FALSE, 0);

  label5 = gtk_label_new_with_mnemonic (_("Rechercher un capteur"));
  gtk_widget_show (label5);
  gtk_box_pack_start (GTK_BOX (hbox4), label5, FALSE, FALSE, 0);

  button_deconnexion_gestion = gtk_button_new ();
  gtk_widget_show (button_deconnexion_gestion);
  gtk_fixed_put (GTK_FIXED (fixed1), button_deconnexion_gestion, 0, 8);
  gtk_widget_set_size_request (button_deconnexion_gestion, 128, 48);

  alignment19 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment19);
  gtk_container_add (GTK_CONTAINER (button_deconnexion_gestion), alignment19);

  hbox19 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox19);
  gtk_container_add (GTK_CONTAINER (alignment19), hbox19);

  image19 = gtk_image_new_from_stock ("gtk-quit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image19);
  gtk_box_pack_start (GTK_BOX (hbox19), image19, FALSE, FALSE, 0);

  label43 = gtk_label_new_with_mnemonic (_("Quitter"));
  gtk_widget_show (label43);
  gtk_box_pack_start (GTK_BOX (hbox19), label43, FALSE, FALSE, 0);

  button_hors_norme = gtk_button_new ();
  gtk_widget_show (button_hors_norme);
  gtk_fixed_put (GTK_FIXED (fixed1), button_hors_norme, 784, 408);
  gtk_widget_set_size_request (button_hors_norme, 216, 48);

  alignment20 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment20);
  gtk_container_add (GTK_CONTAINER (button_hors_norme), alignment20);

  hbox20 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox20);
  gtk_container_add (GTK_CONTAINER (alignment20), hbox20);

  image20 = gtk_image_new_from_stock ("gtk-dialog-warning", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image20);
  gtk_box_pack_start (GTK_BOX (hbox20), image20, FALSE, FALSE, 0);

  label44 = gtk_label_new_with_mnemonic (_("Capteur hors norme"));
  gtk_widget_show (label44);
  gtk_box_pack_start (GTK_BOX (hbox20), label44, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) button_supprimer_gestion, "clicked",
                    G_CALLBACK (on_button_supprimer_gestion_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_modifier_gestion, "clicked",
                    G_CALLBACK (on_button_modifier_gestion_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_ajout_gestion, "clicked",
                    G_CALLBACK (on_button_ajout_gestion_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_rechercher_gestion, "clicked",
                    G_CALLBACK (on_button_rechercher_gestion_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_deconnexion_gestion, "clicked",
                    G_CALLBACK (gtk_main_quit),
                    NULL);
  g_signal_connect ((gpointer) button_hors_norme, "clicked",
                    G_CALLBACK (on_button_hors_norme_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window1_gestion, window1_gestion, "window1_gestion");
  GLADE_HOOKUP_OBJECT (window1_gestion, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (window1_gestion, label1, "label1");
  GLADE_HOOKUP_OBJECT (window1_gestion, button_supprimer_gestion, "button_supprimer_gestion");
  GLADE_HOOKUP_OBJECT (window1_gestion, alignment3, "alignment3");
  GLADE_HOOKUP_OBJECT (window1_gestion, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (window1_gestion, image3, "image3");
  GLADE_HOOKUP_OBJECT (window1_gestion, label4, "label4");
  GLADE_HOOKUP_OBJECT (window1_gestion, button_modifier_gestion, "button_modifier_gestion");
  GLADE_HOOKUP_OBJECT (window1_gestion, alignment2, "alignment2");
  GLADE_HOOKUP_OBJECT (window1_gestion, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (window1_gestion, image2, "image2");
  GLADE_HOOKUP_OBJECT (window1_gestion, label3, "label3");
  GLADE_HOOKUP_OBJECT (window1_gestion, button_ajout_gestion, "button_ajout_gestion");
  GLADE_HOOKUP_OBJECT (window1_gestion, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (window1_gestion, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (window1_gestion, image1, "image1");
  GLADE_HOOKUP_OBJECT (window1_gestion, label2, "label2");
  GLADE_HOOKUP_OBJECT (window1_gestion, treeview1, "treeview1");
  GLADE_HOOKUP_OBJECT (window1_gestion, button_rechercher_gestion, "button_rechercher_gestion");
  GLADE_HOOKUP_OBJECT (window1_gestion, alignment4, "alignment4");
  GLADE_HOOKUP_OBJECT (window1_gestion, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (window1_gestion, image4, "image4");
  GLADE_HOOKUP_OBJECT (window1_gestion, label5, "label5");
  GLADE_HOOKUP_OBJECT (window1_gestion, button_deconnexion_gestion, "button_deconnexion_gestion");
  GLADE_HOOKUP_OBJECT (window1_gestion, alignment19, "alignment19");
  GLADE_HOOKUP_OBJECT (window1_gestion, hbox19, "hbox19");
  GLADE_HOOKUP_OBJECT (window1_gestion, image19, "image19");
  GLADE_HOOKUP_OBJECT (window1_gestion, label43, "label43");
  GLADE_HOOKUP_OBJECT (window1_gestion, button_hors_norme, "button_hors_norme");
  GLADE_HOOKUP_OBJECT (window1_gestion, alignment20, "alignment20");
  GLADE_HOOKUP_OBJECT (window1_gestion, hbox20, "hbox20");
  GLADE_HOOKUP_OBJECT (window1_gestion, image20, "image20");
  GLADE_HOOKUP_OBJECT (window1_gestion, label44, "label44");

  return window1_gestion;
}

GtkWidget*
create_window2_liste (void)
{
  GtkWidget *window2_liste;
  GtkWidget *fixed2;
  GtkWidget *entry1;
  GtkWidget *treeview3;
  GtkWidget *label8;
  GtkWidget *label9;
  GtkWidget *button_rechercher_liste;
  GtkWidget *alignment7;
  GtkWidget *hbox7;
  GtkWidget *image7;
  GtkWidget *label10;
  GtkWidget *button_retour_liste;
  GtkWidget *alignment8;
  GtkWidget *hbox8;
  GtkWidget *image8;
  GtkWidget *label11;

  window2_liste = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window2_liste), _("Liste des capteurs"));

  fixed2 = gtk_fixed_new ();
  gtk_widget_show (fixed2);
  gtk_container_add (GTK_CONTAINER (window2_liste), fixed2);

  entry1 = gtk_entry_new ();
  gtk_widget_show (entry1);
  gtk_fixed_put (GTK_FIXED (fixed2), entry1, 272, 88);
  gtk_widget_set_size_request (entry1, 176, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry1), 8226);

  treeview3 = gtk_tree_view_new ();
  gtk_widget_show (treeview3);
  gtk_fixed_put (GTK_FIXED (fixed2), treeview3, 32, 232);
  gtk_widget_set_size_request (treeview3, 920, 120);

  label8 = gtk_label_new (_("ID \303\240 rechercher :"));
  gtk_widget_show (label8);
  gtk_fixed_put (GTK_FIXED (fixed2), label8, 104, 80);
  gtk_widget_set_size_request (label8, 152, 48);

  label9 = gtk_label_new (_("Si le capteur existe, le r\303\251sultat sera affich\303\251 ici :"));
  gtk_widget_show (label9);
  gtk_fixed_put (GTK_FIXED (fixed2), label9, 104, 160);
  gtk_widget_set_size_request (label9, 352, 48);

  button_rechercher_liste = gtk_button_new ();
  gtk_widget_show (button_rechercher_liste);
  gtk_fixed_put (GTK_FIXED (fixed2), button_rechercher_liste, 544, 112);
  gtk_widget_set_size_request (button_rechercher_liste, 216, 48);

  alignment7 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment7);
  gtk_container_add (GTK_CONTAINER (button_rechercher_liste), alignment7);

  hbox7 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox7);
  gtk_container_add (GTK_CONTAINER (alignment7), hbox7);

  image7 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image7);
  gtk_box_pack_start (GTK_BOX (hbox7), image7, FALSE, FALSE, 0);

  label10 = gtk_label_new_with_mnemonic (_("Rechercher"));
  gtk_widget_show (label10);
  gtk_box_pack_start (GTK_BOX (hbox7), label10, FALSE, FALSE, 0);

  button_retour_liste = gtk_button_new ();
  gtk_widget_show (button_retour_liste);
  gtk_fixed_put (GTK_FIXED (fixed2), button_retour_liste, 24, 360);
  gtk_widget_set_size_request (button_retour_liste, 152, 48);

  alignment8 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment8);
  gtk_container_add (GTK_CONTAINER (button_retour_liste), alignment8);

  hbox8 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox8);
  gtk_container_add (GTK_CONTAINER (alignment8), hbox8);

  image8 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image8);
  gtk_box_pack_start (GTK_BOX (hbox8), image8, FALSE, FALSE, 0);

  label11 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label11);
  gtk_box_pack_start (GTK_BOX (hbox8), label11, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) button_rechercher_liste, "clicked",
                    G_CALLBACK (on_button_rechercher_liste_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_retour_liste, "clicked",
                    G_CALLBACK (on_button_retour_liste_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window2_liste, window2_liste, "window2_liste");
  GLADE_HOOKUP_OBJECT (window2_liste, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (window2_liste, entry1, "entry1");
  GLADE_HOOKUP_OBJECT (window2_liste, treeview3, "treeview3");
  GLADE_HOOKUP_OBJECT (window2_liste, label8, "label8");
  GLADE_HOOKUP_OBJECT (window2_liste, label9, "label9");
  GLADE_HOOKUP_OBJECT (window2_liste, button_rechercher_liste, "button_rechercher_liste");
  GLADE_HOOKUP_OBJECT (window2_liste, alignment7, "alignment7");
  GLADE_HOOKUP_OBJECT (window2_liste, hbox7, "hbox7");
  GLADE_HOOKUP_OBJECT (window2_liste, image7, "image7");
  GLADE_HOOKUP_OBJECT (window2_liste, label10, "label10");
  GLADE_HOOKUP_OBJECT (window2_liste, button_retour_liste, "button_retour_liste");
  GLADE_HOOKUP_OBJECT (window2_liste, alignment8, "alignment8");
  GLADE_HOOKUP_OBJECT (window2_liste, hbox8, "hbox8");
  GLADE_HOOKUP_OBJECT (window2_liste, image8, "image8");
  GLADE_HOOKUP_OBJECT (window2_liste, label11, "label11");

  return window2_liste;
}

GtkWidget*
create_window3_supp (void)
{
  GtkWidget *window3_supp;
  GtkWidget *fixed3;
  GtkWidget *entry2;
  GtkWidget *label12;
  GtkWidget *button_retour_suppression;
  GtkWidget *alignment11;
  GtkWidget *hbox11;
  GtkWidget *image11;
  GtkWidget *label15;
  GtkWidget *checkbutton_supp;
  GtkWidget *alignment9;
  GtkWidget *hbox9;
  GtkWidget *image9;
  GtkWidget *label13;
  GtkWidget *button_supprimer_supprission;
  GtkWidget *alignment10;
  GtkWidget *hbox10;
  GtkWidget *image10;
  GtkWidget *label14;
  GtkWidget *label_supp_message;

  window3_supp = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window3_supp), _("supprission d'un capteur"));

  fixed3 = gtk_fixed_new ();
  gtk_widget_show (fixed3);
  gtk_container_add (GTK_CONTAINER (window3_supp), fixed3);

  entry2 = gtk_entry_new ();
  gtk_widget_show (entry2);
  gtk_fixed_put (GTK_FIXED (fixed3), entry2, 272, 56);
  gtk_widget_set_size_request (entry2, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry2), 8226);

  label12 = gtk_label_new (_("ID \303\240 supprimer :"));
  gtk_widget_show (label12);
  gtk_fixed_put (GTK_FIXED (fixed3), label12, 112, 48);
  gtk_widget_set_size_request (label12, 160, 48);

  button_retour_suppression = gtk_button_new ();
  gtk_widget_show (button_retour_suppression);
  gtk_fixed_put (GTK_FIXED (fixed3), button_retour_suppression, 8, 272);
  gtk_widget_set_size_request (button_retour_suppression, 136, 40);

  alignment11 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment11);
  gtk_container_add (GTK_CONTAINER (button_retour_suppression), alignment11);

  hbox11 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox11);
  gtk_container_add (GTK_CONTAINER (alignment11), hbox11);

  image11 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image11);
  gtk_box_pack_start (GTK_BOX (hbox11), image11, FALSE, FALSE, 0);

  label15 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label15);
  gtk_box_pack_start (GTK_BOX (hbox11), label15, FALSE, FALSE, 0);

  checkbutton_supp = gtk_check_button_new ();
  gtk_widget_show (checkbutton_supp);
  gtk_fixed_put (GTK_FIXED (fixed3), checkbutton_supp, 216, 128);
  gtk_widget_set_size_request (checkbutton_supp, 118, 24);

  alignment9 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment9);
  gtk_container_add (GTK_CONTAINER (checkbutton_supp), alignment9);

  hbox9 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox9);
  gtk_container_add (GTK_CONTAINER (alignment9), hbox9);

  image9 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image9);
  gtk_box_pack_start (GTK_BOX (hbox9), image9, FALSE, FALSE, 0);

  label13 = gtk_label_new_with_mnemonic (_("Confirmer"));
  gtk_widget_show (label13);
  gtk_box_pack_start (GTK_BOX (hbox9), label13, FALSE, FALSE, 0);

  button_supprimer_supprission = gtk_button_new ();
  gtk_widget_show (button_supprimer_supprission);
  gtk_fixed_put (GTK_FIXED (fixed3), button_supprimer_supprission, 152, 208);
  gtk_widget_set_size_request (button_supprimer_supprission, 240, 48);

  alignment10 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment10);
  gtk_container_add (GTK_CONTAINER (button_supprimer_supprission), alignment10);

  hbox10 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox10);
  gtk_container_add (GTK_CONTAINER (alignment10), hbox10);

  image10 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image10);
  gtk_box_pack_start (GTK_BOX (hbox10), image10, FALSE, FALSE, 0);

  label14 = gtk_label_new_with_mnemonic (_("Supprimer"));
  gtk_widget_show (label14);
  gtk_box_pack_start (GTK_BOX (hbox10), label14, FALSE, FALSE, 0);

  label_supp_message = gtk_label_new ("");
  gtk_fixed_put (GTK_FIXED (fixed3), label_supp_message, 152, 160);
  gtk_widget_set_size_request (label_supp_message, 256, 32);

  g_signal_connect ((gpointer) button_retour_suppression, "clicked",
                    G_CALLBACK (on_button_retour_suppression_clicked),
                    NULL);
  g_signal_connect ((gpointer) checkbutton_supp, "toggled",
                    G_CALLBACK (on_checkbutton_supp_toggled),
                    NULL);
  g_signal_connect ((gpointer) button_supprimer_supprission, "clicked",
                    G_CALLBACK (on_button_supprimer_supprission_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window3_supp, window3_supp, "window3_supp");
  GLADE_HOOKUP_OBJECT (window3_supp, fixed3, "fixed3");
  GLADE_HOOKUP_OBJECT (window3_supp, entry2, "entry2");
  GLADE_HOOKUP_OBJECT (window3_supp, label12, "label12");
  GLADE_HOOKUP_OBJECT (window3_supp, button_retour_suppression, "button_retour_suppression");
  GLADE_HOOKUP_OBJECT (window3_supp, alignment11, "alignment11");
  GLADE_HOOKUP_OBJECT (window3_supp, hbox11, "hbox11");
  GLADE_HOOKUP_OBJECT (window3_supp, image11, "image11");
  GLADE_HOOKUP_OBJECT (window3_supp, label15, "label15");
  GLADE_HOOKUP_OBJECT (window3_supp, checkbutton_supp, "checkbutton_supp");
  GLADE_HOOKUP_OBJECT (window3_supp, alignment9, "alignment9");
  GLADE_HOOKUP_OBJECT (window3_supp, hbox9, "hbox9");
  GLADE_HOOKUP_OBJECT (window3_supp, image9, "image9");
  GLADE_HOOKUP_OBJECT (window3_supp, label13, "label13");
  GLADE_HOOKUP_OBJECT (window3_supp, button_supprimer_supprission, "button_supprimer_supprission");
  GLADE_HOOKUP_OBJECT (window3_supp, alignment10, "alignment10");
  GLADE_HOOKUP_OBJECT (window3_supp, hbox10, "hbox10");
  GLADE_HOOKUP_OBJECT (window3_supp, image10, "image10");
  GLADE_HOOKUP_OBJECT (window3_supp, label14, "label14");
  GLADE_HOOKUP_OBJECT (window3_supp, label_supp_message, "label_supp_message");

  return window3_supp;
}

GtkWidget*
create_window4_ajout (void)
{
  GtkWidget *window4_ajout;
  GtkWidget *fixed4;
  GtkWidget *entry_id_ajout;
  GtkWidget *entry_marque_ajout;
  GtkObject *spinbutton1_ajout_adj;
  GtkWidget *spinbutton1_ajout;
  GtkObject *spinbutton2_ajout_adj;
  GtkWidget *spinbutton2_ajout;
  GtkObject *spinbutton3_ajout_adj;
  GtkWidget *spinbutton3_ajout;
  GtkWidget *entry_valmin_ajout;
  GtkWidget *entry_valmax_ajout;
  GtkWidget *label17;
  GtkWidget *label19;
  GtkWidget *label23;
  GtkWidget *label22;
  GtkWidget *label21;
  GtkWidget *label20;
  GtkWidget *label25;
  GtkWidget *label24;
  GtkWidget *label26;
  GtkWidget *label18;
  GtkWidget *combobox1;
  GtkWidget *button_retour_ajout;
  GtkWidget *alignment13;
  GtkWidget *hbox13;
  GtkWidget *image13;
  GtkWidget *label27;
  GtkWidget *radiobutton_debit_ajout;
  GSList *radiobutton_debit_ajout_group = NULL;
  GtkWidget *alignment22;
  GtkWidget *hbox22;
  GtkWidget *image22;
  GtkWidget *label47;
  GtkWidget *radiobutton_fumee_ajout;
  GtkWidget *alignment23;
  GtkWidget *hbox23;
  GtkWidget *image23;
  GtkWidget *label48;
  GtkWidget *radiobutton_temp_ajout;
  GtkWidget *alignment24;
  GtkWidget *hbox24;
  GtkWidget *image24;
  GtkWidget *label49;
  GtkWidget *button_ajouter_ajout;
  GtkWidget *alignment14;
  GtkWidget *hbox14;
  GtkWidget *image14;
  GtkWidget *label28;
  GtkWidget *label_aj_erreur_id;
  GtkWidget *label_aj_erreur_marque;
  GtkWidget *label_aj_erreur_min;
  GtkWidget *label_aj_erreur_max;
  GtkWidget *label_ajut_reussite;

  window4_ajout = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window4_ajout), _("Formulaire d'ajout"));

  fixed4 = gtk_fixed_new ();
  gtk_widget_show (fixed4);
  gtk_container_add (GTK_CONTAINER (window4_ajout), fixed4);

  entry_id_ajout = gtk_entry_new ();
  gtk_widget_show (entry_id_ajout);
  gtk_fixed_put (GTK_FIXED (fixed4), entry_id_ajout, 256, 48);
  gtk_widget_set_size_request (entry_id_ajout, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_id_ajout), 8226);

  entry_marque_ajout = gtk_entry_new ();
  gtk_widget_show (entry_marque_ajout);
  gtk_fixed_put (GTK_FIXED (fixed4), entry_marque_ajout, 256, 104);
  gtk_widget_set_size_request (entry_marque_ajout, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_marque_ajout), 8226);

  spinbutton1_ajout_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  spinbutton1_ajout = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton1_ajout_adj), 1, 0);
  gtk_widget_show (spinbutton1_ajout);
  gtk_fixed_put (GTK_FIXED (fixed4), spinbutton1_ajout, 288, 288);
  gtk_widget_set_size_request (spinbutton1_ajout, 60, 27);

  spinbutton2_ajout_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  spinbutton2_ajout = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton2_ajout_adj), 1, 0);
  gtk_widget_show (spinbutton2_ajout);
  gtk_fixed_put (GTK_FIXED (fixed4), spinbutton2_ajout, 440, 288);
  gtk_widget_set_size_request (spinbutton2_ajout, 60, 27);

  spinbutton3_ajout_adj = gtk_adjustment_new (1, 1990, 2090, 1, 10, 10);
  spinbutton3_ajout = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton3_ajout_adj), 1, 0);
  gtk_widget_show (spinbutton3_ajout);
  gtk_fixed_put (GTK_FIXED (fixed4), spinbutton3_ajout, 592, 288);
  gtk_widget_set_size_request (spinbutton3_ajout, 60, 27);

  entry_valmin_ajout = gtk_entry_new ();
  gtk_widget_show (entry_valmin_ajout);
  gtk_fixed_put (GTK_FIXED (fixed4), entry_valmin_ajout, 232, 368);
  gtk_widget_set_size_request (entry_valmin_ajout, 104, 40);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_valmin_ajout), 8226);

  entry_valmax_ajout = gtk_entry_new ();
  gtk_widget_show (entry_valmax_ajout);
  gtk_fixed_put (GTK_FIXED (fixed4), entry_valmax_ajout, 536, 368);
  gtk_widget_set_size_request (entry_valmax_ajout, 104, 40);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_valmax_ajout), 8226);

  label17 = gtk_label_new (_("ID :"));
  gtk_widget_show (label17);
  gtk_fixed_put (GTK_FIXED (fixed4), label17, 136, 48);
  gtk_widget_set_size_request (label17, 81, 32);

  label19 = gtk_label_new (_("Type :"));
  gtk_widget_show (label19);
  gtk_fixed_put (GTK_FIXED (fixed4), label19, 40, 176);
  gtk_widget_set_size_request (label19, 104, 40);

  label23 = gtk_label_new (_("Ann\303\251e :"));
  gtk_widget_show (label23);
  gtk_fixed_put (GTK_FIXED (fixed4), label23, 520, 280);
  gtk_widget_set_size_request (label23, 72, 41);

  label22 = gtk_label_new (_("Mois :"));
  gtk_widget_show (label22);
  gtk_fixed_put (GTK_FIXED (fixed4), label22, 368, 288);
  gtk_widget_set_size_request (label22, 88, 32);

  label21 = gtk_label_new (_("Jours :"));
  gtk_widget_show (label21);
  gtk_fixed_put (GTK_FIXED (fixed4), label21, 224, 288);
  gtk_widget_set_size_request (label21, 72, 24);

  label20 = gtk_label_new (_("Date de mise \nen marche :"));
  gtk_widget_show (label20);
  gtk_fixed_put (GTK_FIXED (fixed4), label20, 72, 280);
  gtk_widget_set_size_request (label20, 112, 48);

  label25 = gtk_label_new (_("Valeur maximale :"));
  gtk_widget_show (label25);
  gtk_fixed_put (GTK_FIXED (fixed4), label25, 392, 368);
  gtk_widget_set_size_request (label25, 160, 32);

  label24 = gtk_label_new (_("Valeur minimale :"));
  gtk_widget_show (label24);
  gtk_fixed_put (GTK_FIXED (fixed4), label24, 88, 352);
  gtk_widget_set_size_request (label24, 144, 56);

  label26 = gtk_label_new (_("Zone  de coverture :"));
  gtk_widget_show (label26);
  gtk_fixed_put (GTK_FIXED (fixed4), label26, 40, 440);
  gtk_widget_set_size_request (label26, 208, 48);

  label18 = gtk_label_new (_("Marque :"));
  gtk_widget_show (label18);
  gtk_fixed_put (GTK_FIXED (fixed4), label18, 120, 104);
  gtk_widget_set_size_request (label18, 120, 32);

  combobox1 = gtk_combo_box_new_text ();
  gtk_widget_show (combobox1);
  gtk_fixed_put (GTK_FIXED (fixed4), combobox1, 256, 456);
  gtk_widget_set_size_request (combobox1, 208, 40);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("bloc_A"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("bloc_B"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("bloc_C"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("bloc_D"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("bloc_E "));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("bloc_F"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("bloc_J"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("bloc_K"));

  button_retour_ajout = gtk_button_new ();
  gtk_widget_show (button_retour_ajout);
  gtk_fixed_put (GTK_FIXED (fixed4), button_retour_ajout, 8, 536);
  gtk_widget_set_size_request (button_retour_ajout, 120, 40);

  alignment13 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment13);
  gtk_container_add (GTK_CONTAINER (button_retour_ajout), alignment13);

  hbox13 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox13);
  gtk_container_add (GTK_CONTAINER (alignment13), hbox13);

  image13 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image13);
  gtk_box_pack_start (GTK_BOX (hbox13), image13, FALSE, FALSE, 0);

  label27 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label27);
  gtk_box_pack_start (GTK_BOX (hbox13), label27, FALSE, FALSE, 0);

  radiobutton_debit_ajout = gtk_radio_button_new (NULL);
  gtk_widget_show (radiobutton_debit_ajout);
  gtk_fixed_put (GTK_FIXED (fixed4), radiobutton_debit_ajout, 464, 184);
  gtk_widget_set_size_request (radiobutton_debit_ajout, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton_debit_ajout), radiobutton_debit_ajout_group);
  radiobutton_debit_ajout_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton_debit_ajout));

  alignment22 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment22);
  gtk_container_add (GTK_CONTAINER (radiobutton_debit_ajout), alignment22);

  hbox22 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox22);
  gtk_container_add (GTK_CONTAINER (alignment22), hbox22);

  image22 = gtk_image_new_from_stock ("gtk-sort-descending", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image22);
  gtk_box_pack_start (GTK_BOX (hbox22), image22, FALSE, FALSE, 0);

  label47 = gtk_label_new_with_mnemonic (_("D\303\251bit"));
  gtk_widget_show (label47);
  gtk_box_pack_start (GTK_BOX (hbox22), label47, FALSE, FALSE, 0);

  radiobutton_fumee_ajout = gtk_radio_button_new (NULL);
  gtk_widget_show (radiobutton_fumee_ajout);
  gtk_fixed_put (GTK_FIXED (fixed4), radiobutton_fumee_ajout, 320, 184);
  gtk_widget_set_size_request (radiobutton_fumee_ajout, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton_fumee_ajout), radiobutton_debit_ajout_group);
  radiobutton_debit_ajout_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton_fumee_ajout));

  alignment23 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment23);
  gtk_container_add (GTK_CONTAINER (radiobutton_fumee_ajout), alignment23);

  hbox23 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox23);
  gtk_container_add (GTK_CONTAINER (alignment23), hbox23);

  image23 = gtk_image_new_from_stock ("gtk-sort-descending", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image23);
  gtk_box_pack_start (GTK_BOX (hbox23), image23, FALSE, FALSE, 0);

  label48 = gtk_label_new_with_mnemonic (_("Fum\303\251e"));
  gtk_widget_show (label48);
  gtk_box_pack_start (GTK_BOX (hbox23), label48, FALSE, FALSE, 0);

  radiobutton_temp_ajout = gtk_radio_button_new (NULL);
  gtk_widget_show (radiobutton_temp_ajout);
  gtk_fixed_put (GTK_FIXED (fixed4), radiobutton_temp_ajout, 168, 184);
  gtk_widget_set_size_request (radiobutton_temp_ajout, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton_temp_ajout), radiobutton_debit_ajout_group);
  radiobutton_debit_ajout_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton_temp_ajout));

  alignment24 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment24);
  gtk_container_add (GTK_CONTAINER (radiobutton_temp_ajout), alignment24);

  hbox24 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox24);
  gtk_container_add (GTK_CONTAINER (alignment24), hbox24);

  image24 = gtk_image_new_from_stock ("gtk-sort-descending", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image24);
  gtk_box_pack_start (GTK_BOX (hbox24), image24, FALSE, FALSE, 0);

  label49 = gtk_label_new_with_mnemonic (_("T\303\251mperature"));
  gtk_widget_show (label49);
  gtk_box_pack_start (GTK_BOX (hbox24), label49, FALSE, FALSE, 0);

  button_ajouter_ajout = gtk_button_new ();
  gtk_widget_show (button_ajouter_ajout);
  gtk_fixed_put (GTK_FIXED (fixed4), button_ajouter_ajout, 264, 536);
  gtk_widget_set_size_request (button_ajouter_ajout, 192, 40);

  alignment14 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment14);
  gtk_container_add (GTK_CONTAINER (button_ajouter_ajout), alignment14);

  hbox14 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox14);
  gtk_container_add (GTK_CONTAINER (alignment14), hbox14);

  image14 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image14);
  gtk_box_pack_start (GTK_BOX (hbox14), image14, FALSE, FALSE, 0);

  label28 = gtk_label_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (label28);
  gtk_box_pack_start (GTK_BOX (hbox14), label28, FALSE, FALSE, 0);

  label_aj_erreur_id = gtk_label_new (_("Saisir ID !!"));
  gtk_fixed_put (GTK_FIXED (fixed4), label_aj_erreur_id, 280, 80);
  gtk_widget_set_size_request (label_aj_erreur_id, 120, 16);

  label_aj_erreur_marque = gtk_label_new (_("Saisir Marque !!"));
  gtk_fixed_put (GTK_FIXED (fixed4), label_aj_erreur_marque, 272, 136);
  gtk_widget_set_size_request (label_aj_erreur_marque, 128, 16);

  label_aj_erreur_min = gtk_label_new (_("Saisir valeur minimale !!"));
  gtk_fixed_put (GTK_FIXED (fixed4), label_aj_erreur_min, 184, 416);
  gtk_widget_set_size_request (label_aj_erreur_min, 169, 17);

  label_aj_erreur_max = gtk_label_new (_("Saisir valeur Maximale !!"));
  gtk_fixed_put (GTK_FIXED (fixed4), label_aj_erreur_max, 456, 416);
  gtk_widget_set_size_request (label_aj_erreur_max, 192, 17);

  label_ajut_reussite = gtk_label_new (_("Ajouter avec succ\303\251es!"));
  gtk_fixed_put (GTK_FIXED (fixed4), label_ajut_reussite, 240, 496);
  gtk_widget_set_size_request (label_ajut_reussite, 224, 33);

  g_signal_connect ((gpointer) button_retour_ajout, "clicked",
                    G_CALLBACK (on_button_retour_ajout_clicked),
                    NULL);
  g_signal_connect ((gpointer) radiobutton_debit_ajout, "toggled",
                    G_CALLBACK (on_radiobutton_debit_ajout_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobutton_fumee_ajout, "toggled",
                    G_CALLBACK (on_radiobutton_fumee_ajout_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobutton_temp_ajout, "toggled",
                    G_CALLBACK (on_radiobutton_temp_ajout_toggled),
                    NULL);
  g_signal_connect ((gpointer) button_ajouter_ajout, "clicked",
                    G_CALLBACK (on_button_ajouter_ajout_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window4_ajout, window4_ajout, "window4_ajout");
  GLADE_HOOKUP_OBJECT (window4_ajout, fixed4, "fixed4");
  GLADE_HOOKUP_OBJECT (window4_ajout, entry_id_ajout, "entry_id_ajout");
  GLADE_HOOKUP_OBJECT (window4_ajout, entry_marque_ajout, "entry_marque_ajout");
  GLADE_HOOKUP_OBJECT (window4_ajout, spinbutton1_ajout, "spinbutton1_ajout");
  GLADE_HOOKUP_OBJECT (window4_ajout, spinbutton2_ajout, "spinbutton2_ajout");
  GLADE_HOOKUP_OBJECT (window4_ajout, spinbutton3_ajout, "spinbutton3_ajout");
  GLADE_HOOKUP_OBJECT (window4_ajout, entry_valmin_ajout, "entry_valmin_ajout");
  GLADE_HOOKUP_OBJECT (window4_ajout, entry_valmax_ajout, "entry_valmax_ajout");
  GLADE_HOOKUP_OBJECT (window4_ajout, label17, "label17");
  GLADE_HOOKUP_OBJECT (window4_ajout, label19, "label19");
  GLADE_HOOKUP_OBJECT (window4_ajout, label23, "label23");
  GLADE_HOOKUP_OBJECT (window4_ajout, label22, "label22");
  GLADE_HOOKUP_OBJECT (window4_ajout, label21, "label21");
  GLADE_HOOKUP_OBJECT (window4_ajout, label20, "label20");
  GLADE_HOOKUP_OBJECT (window4_ajout, label25, "label25");
  GLADE_HOOKUP_OBJECT (window4_ajout, label24, "label24");
  GLADE_HOOKUP_OBJECT (window4_ajout, label26, "label26");
  GLADE_HOOKUP_OBJECT (window4_ajout, label18, "label18");
  GLADE_HOOKUP_OBJECT (window4_ajout, combobox1, "combobox1");
  GLADE_HOOKUP_OBJECT (window4_ajout, button_retour_ajout, "button_retour_ajout");
  GLADE_HOOKUP_OBJECT (window4_ajout, alignment13, "alignment13");
  GLADE_HOOKUP_OBJECT (window4_ajout, hbox13, "hbox13");
  GLADE_HOOKUP_OBJECT (window4_ajout, image13, "image13");
  GLADE_HOOKUP_OBJECT (window4_ajout, label27, "label27");
  GLADE_HOOKUP_OBJECT (window4_ajout, radiobutton_debit_ajout, "radiobutton_debit_ajout");
  GLADE_HOOKUP_OBJECT (window4_ajout, alignment22, "alignment22");
  GLADE_HOOKUP_OBJECT (window4_ajout, hbox22, "hbox22");
  GLADE_HOOKUP_OBJECT (window4_ajout, image22, "image22");
  GLADE_HOOKUP_OBJECT (window4_ajout, label47, "label47");
  GLADE_HOOKUP_OBJECT (window4_ajout, radiobutton_fumee_ajout, "radiobutton_fumee_ajout");
  GLADE_HOOKUP_OBJECT (window4_ajout, alignment23, "alignment23");
  GLADE_HOOKUP_OBJECT (window4_ajout, hbox23, "hbox23");
  GLADE_HOOKUP_OBJECT (window4_ajout, image23, "image23");
  GLADE_HOOKUP_OBJECT (window4_ajout, label48, "label48");
  GLADE_HOOKUP_OBJECT (window4_ajout, radiobutton_temp_ajout, "radiobutton_temp_ajout");
  GLADE_HOOKUP_OBJECT (window4_ajout, alignment24, "alignment24");
  GLADE_HOOKUP_OBJECT (window4_ajout, hbox24, "hbox24");
  GLADE_HOOKUP_OBJECT (window4_ajout, image24, "image24");
  GLADE_HOOKUP_OBJECT (window4_ajout, label49, "label49");
  GLADE_HOOKUP_OBJECT (window4_ajout, button_ajouter_ajout, "button_ajouter_ajout");
  GLADE_HOOKUP_OBJECT (window4_ajout, alignment14, "alignment14");
  GLADE_HOOKUP_OBJECT (window4_ajout, hbox14, "hbox14");
  GLADE_HOOKUP_OBJECT (window4_ajout, image14, "image14");
  GLADE_HOOKUP_OBJECT (window4_ajout, label28, "label28");
  GLADE_HOOKUP_OBJECT (window4_ajout, label_aj_erreur_id, "label_aj_erreur_id");
  GLADE_HOOKUP_OBJECT (window4_ajout, label_aj_erreur_marque, "label_aj_erreur_marque");
  GLADE_HOOKUP_OBJECT (window4_ajout, label_aj_erreur_min, "label_aj_erreur_min");
  GLADE_HOOKUP_OBJECT (window4_ajout, label_aj_erreur_max, "label_aj_erreur_max");
  GLADE_HOOKUP_OBJECT (window4_ajout, label_ajut_reussite, "label_ajut_reussite");

  return window4_ajout;
}

GtkWidget*
create_window5_modif (void)
{
  GtkWidget *window5_modif;
  GtkWidget *fixed5;
  GtkWidget *entry_id_modif;
  GtkWidget *entry_marque_modif;
  GtkObject *spinbutton4_modif_adj;
  GtkWidget *spinbutton4_modif;
  GtkObject *spinbutton5_modif_adj;
  GtkWidget *spinbutton5_modif;
  GtkObject *spinbutton6_modif_adj;
  GtkWidget *spinbutton6_modif;
  GtkWidget *entry_valmin_modif;
  GtkWidget *entry_valmax_modif;
  GtkWidget *label31;
  GtkWidget *label30;
  GtkWidget *label32;
  GtkWidget *label34;
  GtkWidget *label35;
  GtkWidget *label36;
  GtkWidget *label38;
  GtkWidget *label37;
  GtkWidget *label39;
  GtkWidget *button_retour_modification;
  GtkWidget *alignment16;
  GtkWidget *hbox16;
  GtkWidget *image16;
  GtkWidget *label40;
  GtkWidget *label33;
  GtkWidget *radiobutton_temp_moodif;
  GSList *radiobutton_temp_moodif_group = NULL;
  GtkWidget *alignment25;
  GtkWidget *hbox25;
  GtkWidget *image25;
  GtkWidget *label50;
  GtkWidget *radiobutton_fum_modif;
  GtkWidget *alignment26;
  GtkWidget *hbox26;
  GtkWidget *image26;
  GtkWidget *label51;
  GtkWidget *radiobutton_debit_modif;
  GtkWidget *alignment27;
  GtkWidget *hbox27;
  GtkWidget *image27;
  GtkWidget *label52;
  GtkWidget *button_modifier_modification;
  GtkWidget *alignment17;
  GtkWidget *hbox17;
  GtkWidget *image17;
  GtkWidget *label41;
  GtkWidget *combobox2;

  window5_modif = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window5_modif), _("Formulaire de modification"));

  fixed5 = gtk_fixed_new ();
  gtk_widget_show (fixed5);
  gtk_container_add (GTK_CONTAINER (window5_modif), fixed5);

  entry_id_modif = gtk_entry_new ();
  gtk_widget_show (entry_id_modif);
  gtk_fixed_put (GTK_FIXED (fixed5), entry_id_modif, 256, 64);
  gtk_widget_set_size_request (entry_id_modif, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_id_modif), 8226);

  entry_marque_modif = gtk_entry_new ();
  gtk_widget_show (entry_marque_modif);
  gtk_fixed_put (GTK_FIXED (fixed5), entry_marque_modif, 256, 128);
  gtk_widget_set_size_request (entry_marque_modif, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_marque_modif), 8226);

  spinbutton4_modif_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  spinbutton4_modif = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton4_modif_adj), 1, 0);
  gtk_widget_show (spinbutton4_modif);
  gtk_fixed_put (GTK_FIXED (fixed5), spinbutton4_modif, 288, 288);
  gtk_widget_set_size_request (spinbutton4_modif, 60, 27);

  spinbutton5_modif_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  spinbutton5_modif = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton5_modif_adj), 1, 0);
  gtk_widget_show (spinbutton5_modif);
  gtk_fixed_put (GTK_FIXED (fixed5), spinbutton5_modif, 440, 288);
  gtk_widget_set_size_request (spinbutton5_modif, 60, 27);

  spinbutton6_modif_adj = gtk_adjustment_new (1, 1990, 2090, 1, 10, 10);
  spinbutton6_modif = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton6_modif_adj), 1, 0);
  gtk_widget_show (spinbutton6_modif);
  gtk_fixed_put (GTK_FIXED (fixed5), spinbutton6_modif, 608, 288);
  gtk_widget_set_size_request (spinbutton6_modif, 60, 27);

  entry_valmin_modif = gtk_entry_new ();
  gtk_widget_show (entry_valmin_modif);
  gtk_fixed_put (GTK_FIXED (fixed5), entry_valmin_modif, 192, 376);
  gtk_widget_set_size_request (entry_valmin_modif, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_valmin_modif), 8226);

  entry_valmax_modif = gtk_entry_new ();
  gtk_widget_show (entry_valmax_modif);
  gtk_fixed_put (GTK_FIXED (fixed5), entry_valmax_modif, 528, 376);
  gtk_widget_set_size_request (entry_valmax_modif, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_valmax_modif), 8226);

  label31 = gtk_label_new (_("Marque :"));
  gtk_widget_show (label31);
  gtk_fixed_put (GTK_FIXED (fixed5), label31, 176, 120);
  gtk_widget_set_size_request (label31, 88, 40);

  label30 = gtk_label_new (_("ID :"));
  gtk_widget_show (label30);
  gtk_fixed_put (GTK_FIXED (fixed5), label30, 176, 64);
  gtk_widget_set_size_request (label30, 112, 32);

  label32 = gtk_label_new (_("Type :"));
  gtk_widget_show (label32);
  gtk_fixed_put (GTK_FIXED (fixed5), label32, 88, 192);
  gtk_widget_set_size_request (label32, 120, 40);

  label34 = gtk_label_new (_("Jours :"));
  gtk_widget_show (label34);
  gtk_fixed_put (GTK_FIXED (fixed5), label34, 208, 288);
  gtk_widget_set_size_request (label34, 72, 32);

  label35 = gtk_label_new (_("Mois :"));
  gtk_widget_show (label35);
  gtk_fixed_put (GTK_FIXED (fixed5), label35, 376, 288);
  gtk_widget_set_size_request (label35, 64, 32);

  label36 = gtk_label_new (_("Ann\303\251e :"));
  gtk_widget_show (label36);
  gtk_fixed_put (GTK_FIXED (fixed5), label36, 544, 288);
  gtk_widget_set_size_request (label36, 56, 32);

  label38 = gtk_label_new (_("Valeur maximale :"));
  gtk_widget_show (label38);
  gtk_fixed_put (GTK_FIXED (fixed5), label38, 384, 368);
  gtk_widget_set_size_request (label38, 145, 40);

  label37 = gtk_label_new (_("Valeur minimale :"));
  gtk_widget_show (label37);
  gtk_fixed_put (GTK_FIXED (fixed5), label37, 32, 352);
  gtk_widget_set_size_request (label37, 176, 72);

  label39 = gtk_label_new (_("Zone de coverture :"));
  gtk_widget_show (label39);
  gtk_fixed_put (GTK_FIXED (fixed5), label39, 24, 456);
  gtk_widget_set_size_request (label39, 192, 40);

  button_retour_modification = gtk_button_new ();
  gtk_widget_show (button_retour_modification);
  gtk_fixed_put (GTK_FIXED (fixed5), button_retour_modification, 0, 512);
  gtk_widget_set_size_request (button_retour_modification, 128, 40);

  alignment16 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment16);
  gtk_container_add (GTK_CONTAINER (button_retour_modification), alignment16);

  hbox16 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox16);
  gtk_container_add (GTK_CONTAINER (alignment16), hbox16);

  image16 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image16);
  gtk_box_pack_start (GTK_BOX (hbox16), image16, FALSE, FALSE, 0);

  label40 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label40);
  gtk_box_pack_start (GTK_BOX (hbox16), label40, FALSE, FALSE, 0);

  label33 = gtk_label_new (_("Date de mise \nen marche :"));
  gtk_widget_show (label33);
  gtk_fixed_put (GTK_FIXED (fixed5), label33, 96, 280);
  gtk_widget_set_size_request (label33, 120, 48);

  radiobutton_temp_moodif = gtk_radio_button_new (NULL);
  gtk_widget_show (radiobutton_temp_moodif);
  gtk_fixed_put (GTK_FIXED (fixed5), radiobutton_temp_moodif, 224, 200);
  gtk_widget_set_size_request (radiobutton_temp_moodif, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton_temp_moodif), radiobutton_temp_moodif_group);
  radiobutton_temp_moodif_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton_temp_moodif));

  alignment25 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment25);
  gtk_container_add (GTK_CONTAINER (radiobutton_temp_moodif), alignment25);

  hbox25 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox25);
  gtk_container_add (GTK_CONTAINER (alignment25), hbox25);

  image25 = gtk_image_new_from_stock ("gtk-sort-descending", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image25);
  gtk_box_pack_start (GTK_BOX (hbox25), image25, FALSE, FALSE, 0);

  label50 = gtk_label_new_with_mnemonic (_("T\303\251mperature"));
  gtk_widget_show (label50);
  gtk_box_pack_start (GTK_BOX (hbox25), label50, FALSE, FALSE, 0);

  radiobutton_fum_modif = gtk_radio_button_new (NULL);
  gtk_widget_show (radiobutton_fum_modif);
  gtk_fixed_put (GTK_FIXED (fixed5), radiobutton_fum_modif, 392, 200);
  gtk_widget_set_size_request (radiobutton_fum_modif, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton_fum_modif), radiobutton_temp_moodif_group);
  radiobutton_temp_moodif_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton_fum_modif));

  alignment26 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment26);
  gtk_container_add (GTK_CONTAINER (radiobutton_fum_modif), alignment26);

  hbox26 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox26);
  gtk_container_add (GTK_CONTAINER (alignment26), hbox26);

  image26 = gtk_image_new_from_stock ("gtk-sort-descending", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image26);
  gtk_box_pack_start (GTK_BOX (hbox26), image26, FALSE, FALSE, 0);

  label51 = gtk_label_new_with_mnemonic (_("Fum\303\251e"));
  gtk_widget_show (label51);
  gtk_box_pack_start (GTK_BOX (hbox26), label51, FALSE, FALSE, 0);

  radiobutton_debit_modif = gtk_radio_button_new (NULL);
  gtk_widget_show (radiobutton_debit_modif);
  gtk_fixed_put (GTK_FIXED (fixed5), radiobutton_debit_modif, 512, 200);
  gtk_widget_set_size_request (radiobutton_debit_modif, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton_debit_modif), radiobutton_temp_moodif_group);
  radiobutton_temp_moodif_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton_debit_modif));

  alignment27 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment27);
  gtk_container_add (GTK_CONTAINER (radiobutton_debit_modif), alignment27);

  hbox27 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox27);
  gtk_container_add (GTK_CONTAINER (alignment27), hbox27);

  image27 = gtk_image_new_from_stock ("gtk-sort-descending", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image27);
  gtk_box_pack_start (GTK_BOX (hbox27), image27, FALSE, FALSE, 0);

  label52 = gtk_label_new_with_mnemonic (_("D\303\251bit"));
  gtk_widget_show (label52);
  gtk_box_pack_start (GTK_BOX (hbox27), label52, FALSE, FALSE, 0);

  button_modifier_modification = gtk_button_new ();
  gtk_widget_show (button_modifier_modification);
  gtk_fixed_put (GTK_FIXED (fixed5), button_modifier_modification, 264, 512);
  gtk_widget_set_size_request (button_modifier_modification, 168, 40);

  alignment17 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment17);
  gtk_container_add (GTK_CONTAINER (button_modifier_modification), alignment17);

  hbox17 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox17);
  gtk_container_add (GTK_CONTAINER (alignment17), hbox17);

  image17 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image17);
  gtk_box_pack_start (GTK_BOX (hbox17), image17, FALSE, FALSE, 0);

  label41 = gtk_label_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (label41);
  gtk_box_pack_start (GTK_BOX (hbox17), label41, FALSE, FALSE, 0);

  combobox2 = gtk_combo_box_new_text ();
  gtk_widget_show (combobox2);
  gtk_fixed_put (GTK_FIXED (fixed5), combobox2, 248, 448);
  gtk_widget_set_size_request (combobox2, 208, 47);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox2), _("bloc_A"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox2), _("bloc_B"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox2), _("bloc_C"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox2), _("bloc_D"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox2), _("bloc_E "));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox2), _("bloc_F"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox2), _("bloc_J"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox2), _("bloc_K"));

  g_signal_connect ((gpointer) button_retour_modification, "clicked",
                    G_CALLBACK (on_button_retour_modification_clicked),
                    NULL);
  g_signal_connect ((gpointer) radiobutton_temp_moodif, "toggled",
                    G_CALLBACK (on_radiobutton_temp_moodif_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobutton_fum_modif, "toggled",
                    G_CALLBACK (on_radiobutton_fum_modif_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobutton_debit_modif, "toggled",
                    G_CALLBACK (on_radiobutton_debit_modif_toggled),
                    NULL);
  g_signal_connect ((gpointer) button_modifier_modification, "clicked",
                    G_CALLBACK (on_button_modifier_modification_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window5_modif, window5_modif, "window5_modif");
  GLADE_HOOKUP_OBJECT (window5_modif, fixed5, "fixed5");
  GLADE_HOOKUP_OBJECT (window5_modif, entry_id_modif, "entry_id_modif");
  GLADE_HOOKUP_OBJECT (window5_modif, entry_marque_modif, "entry_marque_modif");
  GLADE_HOOKUP_OBJECT (window5_modif, spinbutton4_modif, "spinbutton4_modif");
  GLADE_HOOKUP_OBJECT (window5_modif, spinbutton5_modif, "spinbutton5_modif");
  GLADE_HOOKUP_OBJECT (window5_modif, spinbutton6_modif, "spinbutton6_modif");
  GLADE_HOOKUP_OBJECT (window5_modif, entry_valmin_modif, "entry_valmin_modif");
  GLADE_HOOKUP_OBJECT (window5_modif, entry_valmax_modif, "entry_valmax_modif");
  GLADE_HOOKUP_OBJECT (window5_modif, label31, "label31");
  GLADE_HOOKUP_OBJECT (window5_modif, label30, "label30");
  GLADE_HOOKUP_OBJECT (window5_modif, label32, "label32");
  GLADE_HOOKUP_OBJECT (window5_modif, label34, "label34");
  GLADE_HOOKUP_OBJECT (window5_modif, label35, "label35");
  GLADE_HOOKUP_OBJECT (window5_modif, label36, "label36");
  GLADE_HOOKUP_OBJECT (window5_modif, label38, "label38");
  GLADE_HOOKUP_OBJECT (window5_modif, label37, "label37");
  GLADE_HOOKUP_OBJECT (window5_modif, label39, "label39");
  GLADE_HOOKUP_OBJECT (window5_modif, button_retour_modification, "button_retour_modification");
  GLADE_HOOKUP_OBJECT (window5_modif, alignment16, "alignment16");
  GLADE_HOOKUP_OBJECT (window5_modif, hbox16, "hbox16");
  GLADE_HOOKUP_OBJECT (window5_modif, image16, "image16");
  GLADE_HOOKUP_OBJECT (window5_modif, label40, "label40");
  GLADE_HOOKUP_OBJECT (window5_modif, label33, "label33");
  GLADE_HOOKUP_OBJECT (window5_modif, radiobutton_temp_moodif, "radiobutton_temp_moodif");
  GLADE_HOOKUP_OBJECT (window5_modif, alignment25, "alignment25");
  GLADE_HOOKUP_OBJECT (window5_modif, hbox25, "hbox25");
  GLADE_HOOKUP_OBJECT (window5_modif, image25, "image25");
  GLADE_HOOKUP_OBJECT (window5_modif, label50, "label50");
  GLADE_HOOKUP_OBJECT (window5_modif, radiobutton_fum_modif, "radiobutton_fum_modif");
  GLADE_HOOKUP_OBJECT (window5_modif, alignment26, "alignment26");
  GLADE_HOOKUP_OBJECT (window5_modif, hbox26, "hbox26");
  GLADE_HOOKUP_OBJECT (window5_modif, image26, "image26");
  GLADE_HOOKUP_OBJECT (window5_modif, label51, "label51");
  GLADE_HOOKUP_OBJECT (window5_modif, radiobutton_debit_modif, "radiobutton_debit_modif");
  GLADE_HOOKUP_OBJECT (window5_modif, alignment27, "alignment27");
  GLADE_HOOKUP_OBJECT (window5_modif, hbox27, "hbox27");
  GLADE_HOOKUP_OBJECT (window5_modif, image27, "image27");
  GLADE_HOOKUP_OBJECT (window5_modif, label52, "label52");
  GLADE_HOOKUP_OBJECT (window5_modif, button_modifier_modification, "button_modifier_modification");
  GLADE_HOOKUP_OBJECT (window5_modif, alignment17, "alignment17");
  GLADE_HOOKUP_OBJECT (window5_modif, hbox17, "hbox17");
  GLADE_HOOKUP_OBJECT (window5_modif, image17, "image17");
  GLADE_HOOKUP_OBJECT (window5_modif, label41, "label41");
  GLADE_HOOKUP_OBJECT (window5_modif, combobox2, "combobox2");

  return window5_modif;
}

GtkWidget*
create_window6_hors_norme (void)
{
  GtkWidget *window6_hors_norme;
  GtkWidget *fixed6;
  GtkWidget *treeview4;
  GtkWidget *button_retour_hors_norme;
  GtkWidget *alignment21;
  GtkWidget *hbox21;
  GtkWidget *image21;
  GtkWidget *label46;
  GtkWidget *label_hors_norme_message;

  window6_hors_norme = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window6_hors_norme), _("Capteur(s) hors norme"));

  fixed6 = gtk_fixed_new ();
  gtk_widget_show (fixed6);
  gtk_container_add (GTK_CONTAINER (window6_hors_norme), fixed6);

  treeview4 = gtk_tree_view_new ();
  gtk_widget_show (treeview4);
  gtk_fixed_put (GTK_FIXED (fixed6), treeview4, 72, 136);
  gtk_widget_set_size_request (treeview4, 816, 176);

  button_retour_hors_norme = gtk_button_new ();
  gtk_widget_show (button_retour_hors_norme);
  gtk_fixed_put (GTK_FIXED (fixed6), button_retour_hors_norme, 48, 376);
  gtk_widget_set_size_request (button_retour_hors_norme, 88, 48);

  alignment21 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment21);
  gtk_container_add (GTK_CONTAINER (button_retour_hors_norme), alignment21);

  hbox21 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox21);
  gtk_container_add (GTK_CONTAINER (alignment21), hbox21);

  image21 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image21);
  gtk_box_pack_start (GTK_BOX (hbox21), image21, FALSE, FALSE, 0);

  label46 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label46);
  gtk_box_pack_start (GTK_BOX (hbox21), label46, FALSE, FALSE, 0);

  label_hors_norme_message = gtk_label_new (_("Aucun capteur hors norme tourv\303\251!"));
  gtk_fixed_put (GTK_FIXED (fixed6), label_hors_norme_message, 200, 56);
  gtk_widget_set_size_request (label_hors_norme_message, 304, 40);

  g_signal_connect ((gpointer) button_retour_hors_norme, "clicked",
                    G_CALLBACK (on_button_retour_hors_norme_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window6_hors_norme, window6_hors_norme, "window6_hors_norme");
  GLADE_HOOKUP_OBJECT (window6_hors_norme, fixed6, "fixed6");
  GLADE_HOOKUP_OBJECT (window6_hors_norme, treeview4, "treeview4");
  GLADE_HOOKUP_OBJECT (window6_hors_norme, button_retour_hors_norme, "button_retour_hors_norme");
  GLADE_HOOKUP_OBJECT (window6_hors_norme, alignment21, "alignment21");
  GLADE_HOOKUP_OBJECT (window6_hors_norme, hbox21, "hbox21");
  GLADE_HOOKUP_OBJECT (window6_hors_norme, image21, "image21");
  GLADE_HOOKUP_OBJECT (window6_hors_norme, label46, "label46");
  GLADE_HOOKUP_OBJECT (window6_hors_norme, label_hors_norme_message, "label_hors_norme_message");

  return window6_hors_norme;
}

