/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_window1_gestion (void);
GtkWidget* create_window2_liste (void);
GtkWidget* create_window3_supp (void);
GtkWidget* create_window4_ajout (void);
GtkWidget* create_window5_modif (void);
GtkWidget* create_window6_hors_norme (void);
